Memory testing gen fix insert/ extract generator function
vellvm/vellvm pull request #225
Opened 2022-06-02 16:05 UTC by Hchen201205

Run `make qc-tests` now can generate insert / extract element / value function

2022-06-03 18:04 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +  Program Fixpoint gen_sized_typ_size (sz : nat){measure sz} : GenLLVM typ :=
Can you get rid of these whitespace changes to this function?

2022-06-03 18:04 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +(* TODO: code for ptrtoint incomplete
Let's take this out of this change for now.

2022-06-03 18:04 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +Fixpoint clear_ctx (t: typ) :=
What does this function actually do? I'd expect the `clear_ctx` that we talked about before to only take in an arbitrary generator (not necessarily one for expressions) and produce a new one.

2022-06-03 18:04 UTC, Chobbes commented on src/coq/QC/GenAST.v
>    filter (fun '(_, t) =>
Might be worth adding a little comment about what this filter function is for, I think it's not immediately obvious.

2022-06-03 18:04 UTC, Chobbes commented on src/coq/QC/GenAST.v
>    filter (fun '(_, t) =>
Specifically, what does this call to `filter` do?

2022-06-03 19:51 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +  Program Fixpoint gen_sized_typ_size (sz : nat){measure sz} : GenLLVM typ :=
I think I've adjust this. Please let me know if I miss something. Apologize in advance if I did

2022-06-03 19:51 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +(* TODO: code for ptrtoint incomplete
I've removed them from the code

2022-06-03 19:51 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +Fixpoint clear_ctx (t: typ) :=
Made hide_ctx. Deleted clear_ctx

2022-06-03 19:52 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
>    filter (fun '(_, t) =>
filter will just filter all the vector types, assuming that they are valid. I don't think I can call filter_type because that one actually compares what's inside the vector and I don't want it. I just want to get all the vectors in the ctx.

2022-06-03 20:06 UTC, Chobbes requested changes

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +  Definition hide_ctx {A} (g: GenLLVM A) : GenLLVM A
Let's add a newline between this definition and the previous one.

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
>    Definition append_to_typ_ctx (aliases : list (ident * typ)) : GenLLVM unit
A newline between this definition and previous one would help with reading too.

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        ;ret TYPE_Array <*> lift_GenLLVM genN <*> gen_sized_typ_size sz'
Let's add this space back.

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +(*Example test1 : get_index_paths_aux_xinvec (TYPE_Struct [TYPE_Struct [TYPE_Struct [TYPE_I 8; TYPE_I 8]; TYPE_Vector 2 (TYPE_I 32)]; TYPE_Vector 3 (TYPE_I 1)]) [] = [].
Delete

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +Proof. simpl. *)
Delete

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
>  Definition get_index_paths_agg (t_from: typ) : list (typ * list (Z)) :=
Make sure to leave a newline between the previous definition and this one.

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
>    filter (fun '(_, t) =>
Oh sorry, this isn't the filter I was confused about. Will add another comment...

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
>    filter (fun '(_,path) => match path with
What does this filter do? We should explain this one. Sorry, wrong one last time.

2022-06-03 20:06 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +
Let's delete the trailing whitespace here (there's extra spaces on this line, it's annoying because it shows up in diffs)

2022-06-03 20:08 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +    := ctx <- get_ctx;;
Looks good, I might recommend naming this `saved_ctx` or `old_ctx` or something.

2022-06-04 23:44 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
>    filter (fun '(_,path) => match path with
I think I have a shorter way of writing it, but the reason I have this is that this function is used by `insertvalue` and `extractvalue`, and for convenience in the helper function  I included the prepath, which, because of what we put in as argument, will have one possible choice as nilpath. Therefore, we need to get rid of the nil path because `insertvalue` and `extractvalue` need at least one index.

2022-06-06 13:45 UTC, Chobbes requested changes

2022-06-06 13:45 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +Fixpoint get_index_paths_aux_xinvec (t_from : typ) (pre_path : list Z) {struct t_from}: list (typ * list (Z)) :=
What do these names mean?

2022-06-06 13:48 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +Fixpoint get_index_paths_aux_xinvec (t_from : typ) (pre_path : list Z) {struct t_from}: list (typ * list (Z)) :=
I was running out of names... Basically means get_index_paths_aux but don't get into vec... Please feel free to suggest other names

2022-06-06 14:05 UTC, Chobbes commented
Looks great, thank you!

2022-06-06 14:05 UTC, merged