Added in insertValue insertElement and extractElement
vellvm/vellvm pull request #227
Opened 2022-06-03 18:14 UTC by nsobotka

We added in functionality for these three functions in all three concretize_uvalue spots. Some of the test cases that I wrote for insert and extract value pass, but not all. None of the tests pass for insert and extract element, and I'm not yet sure if that's based on the test cases themselves or the code in Serialization.v

2022-06-03 18:22 UTC, Chobbes requested changes

2022-06-03 18:22 UTC, Chobbes commented on src/coq/Handlers/Serialization.v
> +                  v <- index_into_str_dv str i;;
This doesn't seem right. It looks like you'll do an insertion for each index in `idxs`, but `idxs` is just a path for where you insert a single value into an aggregate type, right?

2022-06-03 18:22 UTC, Chobbes commented on src/coq/Handlers/Serialization.v
> +            let elt_typ := match dvec with
You should use `vec_typ` to get this. `vec_typ` is the type of `vec`.

2022-06-03 18:44 UTC, nsobotka commented on src/coq/Handlers/Serialization.v
> +                  v <- index_into_str_dv str i;;
It only inserts when we are at the last index, otherwise it indexes down a layer

2022-06-03 19:08 UTC, Chobbes commented on src/coq/Handlers/Serialization.v
> +                  v <- index_into_str_dv str i;;
Oh, I see. You're right about that, I misread `index` as `insert` (ugh).

However, I still think this is a mistake, then, no?

If you `index_into_str_dv` you're getting a field from a structure or whatever, so you will end up returning something with the wrong type. You're throwing away the other fields of the structure every time you index, no?

2022-06-03 20:01 UTC, Chobbes requested changes

2022-06-03 20:01 UTC, Chobbes commented on src/coq/Handlers/Serialization.v
> +                      ret v3
Let's call:

- `v` should be `subfield`
- `v2` can be `modified_subfield`

And then let's just kill `v3` and instead of

```
v3 <- insert_into_str str modified_subfield i;;
ret v3
```

We can just have

```
insert_into_str str modified_subfield i
```

2022-06-03 20:01 UTC, Chobbes commented on src/coq/Handlers/Serialization.v
> +            let elt_typ := match vec_typ with
Made another comment, but let's raise an error here instead of introducing a garbage value that might break things in unexpected ways.

2022-06-03 20:01 UTC, Chobbes commented on src/coq/Handlers/Serialization.v
> +  Check concretize_uvalueM.
Delete this.

2022-06-03 20:01 UTC, Chobbes commented on src/coq/Handlers/Serialization.v
> +              | [] => ret str (* What to do? Do we print out some error *)
This is a good point, let's make this raise an error instead of failing silently and terrifyingly.

2022-06-06 16:02 UTC, Chobbes commented
Looks good to me, thank you!

2022-06-06 16:02 UTC, merged