Memory testing gen: ptrtoint and inttoptr generator
vellvm/vellvm pull request #241
Opened 2022-06-08 04:28 UTC by Hchen201205

PR for ptrtoint and inttoptr. Can make and generate both generators. The only case not covered yet is when we want to generate a vector inside the pointer returned from inttoptr (went stack overflow). Shouldn't be a difficult fix but need to give some thought.

2022-06-08 13:30 UTC, Hchen201205 commented
Have stuff to fix... There are some bugs I found

2022-06-08 13:50 UTC, Hchen201205 commented
Bug fixed. Still cannot generate vector. Everytime I move the prime type out to its own function it will give me stack overflow really quick

2022-06-08 14:11 UTC, Chobbes requested changes

2022-06-08 14:11 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +                                    ret (TYPE_Pointer new_typ)
This seems a bit wrong to me.

When you use `ptrtoint` on a vector of pointers, you will get a vector of integers.

When you use `inttoptr` on a vector of integers, you should get a vector of pointers back.

The fact that we return a `TYPE_Pointer` here seems dubious to me. You can't combine everything that's in the vector into one pointer.

2022-06-08 14:11 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +                      end) ctx.
Add a newline between functions so it's easier to pick them out. Otherwise the function bodies and definitions kind of blend together.

2022-06-08 14:13 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +                                    ret (TYPE_Pointer new_typ)
Yes that's a bug. Should be vector of pointer

2022-06-08 14:14 UTC, Chobbes requested changes

2022-06-08 14:14 UTC, Chobbes commented on src/coq/QC/GenAST.v
>    Definition GenLLVM := stateT GenState G.
Newline :).

2022-06-08 14:35 UTC, Chobbes requested changes

2022-06-08 14:35 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +                ++ (if (8 <=? max_byte_sz)%nat then [ret (TYPE_I 8); x <- gen_typ_le_size max_byte_sz;;ret (TYPE_Pointer x)] else [])
For testing we should assume that pointers are 8 bytes wide, I think. They're the same size as an i64. Also a pointer to *any* type is the same size, because a pointer is just a location in memory. That means you can technically make `x` any type, instead of one of a restricted size....

HOWEVER. I don't think we should generate pointers for this, because that means we will cast random integer values etc to pointers, and that location in memory won't be allocated (so when we go to generate loads and stores to those pointers things will explode).

Technically we should make this a parameter because it depends on the memory model, but we can fix the size for now and maybe leave a note + make a github issue about it.

2022-06-08 14:44 UTC, hanxic commented on src/coq/QC/GenAST.v
> +                ++ (if (8 <=? max_byte_sz)%nat then [ret (TYPE_I 8); x <- gen_typ_le_size max_byte_sz;;ret (TYPE_Pointer x)] else [])
I just want to clarify. So are you saying that I should comment out the pointer in this function, for now

2022-06-08 15:25 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +                ++ (if (8 <=? max_byte_sz)%nat then [ret (TYPE_I 8); x <- gen_typ_le_size max_byte_sz;;ret (TYPE_Pointer x)] else [])
Yeah, I think so. Generating pointers here will cause problems.

2022-06-08 15:26 UTC, hanxic commented on src/coq/QC/GenAST.v
> +                ++ (if (8 <=? max_byte_sz)%nat then [ret (TYPE_I 8); x <- gen_typ_le_size max_byte_sz;;ret (TYPE_Pointer x)] else [])
Commented out already in the newest push

2022-06-08 15:56 UTC, Chobbes commented
I think there's a problem still. We will generate a `inttoptr` cast whenever there is something in the `ptrtoint_ctx`. That's fine, *BUT*...

If the type in the context contains a second pointer anywhere (double pointers, structures with pointers, etc), then we should be much more careful. We can't cast to any type with size less than or equal to the original type --- those pointers *MUST* still be pointers. The easy way to handle this for now is to detect when there are pointers contained within the type, and only cast back to the original type instead.

2022-06-08 16:08 UTC, hanxic commented
Cleaned up and solve the problem (I think). I added additional match in `gen_inttoptr` that will check if it is double pointer. If not we will generate new type.

2022-06-08 18:26 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
>    Definition GenLLVM := stateT GenState G.
Sorry. I really need to be more careful on this. Added

2022-06-08 18:57 UTC, Chobbes requested changes

2022-06-08 18:57 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        | TYPE_Pointer _ => (* Double pointer issue *)
I mentioned this in slack, but just to keep it all in one place...

We're going to have to make sure that there are no nested pointers in `old_typ`. That includes double pointers, triple pointers, pointers to structs that contain pointers, structs that contain structs that contain structs that contain arrays that contain pointers, etc... You'll need a recursive function (maybe called something like `typ_contains_pointer`) to check if there's a pointer within a type, can't just be a simple match like this.

2022-06-08 19:01 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +        | TYPE_Pointer _ => (* Double pointer issue *)
Oh ic. So sorry. I simplified the problem. Working on it now. And just to clarify, if there are things like {i32, i32, i32*}, am I able to change i32 into something else and keep i32* or just leave the entire structure unchanged

2022-06-08 19:05 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +        | TYPE_Pointer _ => (* Double pointer issue *)
nvm I see your answer above. Pointer inside the struct will remains, with rest of them changing. Got it

2022-06-08 19:06 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +        | TYPE_Pointer _ => (* Double pointer issue *)
Got it. I will write a recursive function that will see if a type has a pointer, and then will cast if not

2022-06-09 14:47 UTC, Hchen201205 commented
Implemented typ_contains_pointers that will see if the old type (pointer, or vector of pointers, the only two possible input for ptrtoint) contains any double-pointer. Add some catches in generator that allows 0 size array, and not allow 0 size vector.
Not removing `ctx <- get_ctx` will prevent the stack overflow issue. Not sure why delete that will not.

2022-06-09 17:18 UTC, Hchen201205 commented
The force-push happened because there is a solution for #223 that I was supposed to do in another branch...

2022-06-14 13:28 UTC, Chobbes requested changes

2022-06-14 13:28 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        gen_int_typ
HMMMM. I'm realizing that this will actually be a problem.

If you cast a pointer to, say, an `i1`, `i8`, `i32`, or even an `i64` that integer data type may not have enough space to hold the pointer value (technically we have unlimited pointers). In practice `i32` and `i64` conversions should work, but I think we should actually only cast to `TYPE_IPTR` for now. I'd make a `gen_int_typ_for_ptr_cast` (so we can update it later) that you'll use instead of `gen_int_typ` here. It should only return `TYPE_IPTR` for now.

Otherwise if you cast to an `i8` you might truncate the pointer value (or if you cast to an `i1` you almost certainly will). For instance if I allocate something and it gets address `300` an `i8` can't fit that and will truncate the value to `44`... When you go to cast `44` back to a pointer you won't end up pointing to address `300`, you'll be pointing somewhere else. Uh-oh!

This might not be caught with `vellvm` raising an error because we only do `alloca`s to allocate memory, and since we only have one function `main` we never return from a function to pop the stack and free any `alloca`s. Since memory is allocated in order, all lower addresses will be allocated... So when you access `44` it will actually find something and overwrite it. Normally this would be caught with a provenance mismatch, but integers cast to pointers are allowed to accesss any memory.

THAT SAID it should give different behaviour with clang if you end up writing / loading to different points in memory because of this (which you would). I'd be curious why you're not getting a test case failure --- might be good to look into. I'd expect one whenever you cast to an `i1`, so try replacing `gen_int_typ` here with `ret (TYPE_I 1)`... I'd still expect clang to differ on an `i8`, but you won't get any truncation unless you allocate more than 256 bytes in the LLVM program, which we might not because the programs we generate are small.

2022-06-15 10:55 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +        gen_int_typ
I can change that, but shouldn't I also change the show instance. The reason is currently it is `TYPE_IPTR => "iptr"`, which I believe will not pass the syntax check. I can change it to just return "i32*"

2022-06-15 11:02 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +        gen_int_typ
Also I thought you are allowed to truncate pointer? In Langref it said "if value is larger than ty2, the type we will convert to, then a truncation is done."

2022-06-15 15:36 UTC, Chobbes requested changes

2022-06-15 15:36 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +  (* Definition gen_int_typ_for_ptr_cast : GenLLVM typ :=
I think we should still use this function below, just make this return an `i64` instead of an `iptr`. Then if we want to add support for casting to different integer types we have one place we have to change here, and it's a nice named function. Other than that these changes are looking good, and I can get them merged.

2022-06-15 15:46 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        gen_int_typ
You can truncate a pointer, it's just that it would be bad if we truncate it and then try to cast it back to a pointer, because we lose information and can't recreate the original pointer. It's valid to truncate, but we have to be careful to make sure we only produce valid programs, and with how we generate things currently if we truncate we may access unallocated memory.

2022-06-15 16:21 UTC, merged