Memory testing performance: PR #223 on alloca performance
vellvm/vellvm pull request #246
Opened 2022-06-09 18:31 UTC by Hchen201205

Switched `gen_sized_typ` with a new function `gen_sized_typ_ptrinctx` that does a similar thing except has the possibility of generating a pointer only when there is a pointer in the ctx.

2022-06-09 19:11 UTC, Chobbes requested changes

2022-06-09 19:11 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +          if seq.nilp ptrs_in_ctx then '(_,typ) <- oneOf_LLVM (map ret ctx);; ret typ else gen_sized_typ_size_ptrinctx sz' (* If not simply wait till the next size. This will prevent any failGen *)
Hmmmmmmm.

Why call `filter_ptr_typs` if you're just going to pick from anything in the regular context? Picking from the regular context actually isn't a bad idea --- it makes it more likely that we pick a type of an already existing variable. We should probably use `freq_LLVM` to always do that with some weighted probability here and in `gen_sized_typ`. You get more interesting test cases when you reuse variables as parts of the program intermingle more, if that makes sense.

The other thing is I think this would be more efficient if we did the thing where we conditionally append this generator into the list if the context isn't empty, instead of calling it recursively.

2022-06-09 19:18 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +          if seq.nilp ptrs_in_ctx then '(_,typ) <- oneOf_LLVM (map ret ctx);; ret typ else gen_sized_typ_size_ptrinctx sz' (* If not simply wait till the next size. This will prevent any failGen *)
Got it. I didn't know whether I am supposed to use everything in ctx, which is why I use ctx only for one case. I will start changing it to everything in ctx, I will give it a low frequency compared to others so that we won't largely rely on ctx.

The reason why I use recursion is to prevent the tiny possibility that we use something from the ctx, but oneOf_LLVM ctx actually gives a failGen because there isn't anything in the ctx. To rule out the possibility of failGen I recurse, which will generate some other case while also have prim type  as base case.

2022-06-09 19:51 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +          if seq.nilp ptrs_in_ctx then '(_,typ) <- oneOf_LLVM (map ret ctx);; ret typ else gen_sized_typ_size_ptrinctx sz' (* If not simply wait till the next size. This will prevent any failGen *)
I just mean normally we do the trick where we say...

```
oneOf_LLVM ([gen1; gen2] ++ (if there_is_something_in_ctx then [ gen3 ] else [ ]))
```
The advantage is we won't even select `gen3` when it's not meaningful.

2022-06-09 19:56 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +          if seq.nilp ptrs_in_ctx then '(_,typ) <- oneOf_LLVM (map ret ctx);; ret typ else gen_sized_typ_size_ptrinctx sz' (* If not simply wait till the next size. This will prevent any failGen *)
I think it should actually have a fairly high frequency to pick a type that already exists in the context (assuming the context is non-empty). This would make it more likely that we generate programs that actually use variables defined earlier --- instead of creating a bunch of variables that are never used (and never have an impact upon the rest of the execution of the program).

We could even make this frequency clever --- increasing the frequency that we'll reuse a type from the context when the context is larger (i.e., when we've already got a bunch of types in our program, we can make it less likely to generate new ones). This could be a good idea to stop our generators from just generating distinct types of things all the time that can't interopt. I'll make a new issue for this, though.

The other thing is... You just pull `typ` out of `ctx`, but `ctx` may have non-sized types in it, so this is a bug!

2022-06-09 20:53 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +          if seq.nilp ptrs_in_ctx then '(_,typ) <- oneOf_LLVM (map ret ctx);; ret typ else gen_sized_typ_size_ptrinctx sz' (* If not simply wait till the next size. This will prevent any failGen *)
I was using the trick you mentioned but the problem with that is, whenever you do something related to the ctx, you have to return a GenLLVM in the helper. Therefore it has some complication there, I think I have some ideas to do it though.

When context is large enough shouldn't be a big problem. I can have a dummy number there and we can see what large enough is enough.

Can you elaborate on what is the non-sized types? Are you saying that it's illegal because it's size (number of layers in this context) is not the same as what we want?

2022-06-09 23:57 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +          if seq.nilp ptrs_in_ctx then '(_,typ) <- oneOf_LLVM (map ret ctx);; ret typ else gen_sized_typ_size_ptrinctx sz' (* If not simply wait till the next size. This will prevent any failGen *)
Let's just clean this up to do the right thing first, and then worry about #247.

> I was using the trick you mentioned but the problem with that is, whenever you do something related to the ctx, you have to return a GenLLVM in the helper. Therefore it has some complication there, I think I have some ideas to do it though.

I don't follow, it's the same as everywhere else we do this, no?

> Can you elaborate on what is the non-sized types? Are you saying that it's illegal because it's size (number of layers in this context) is not the same as what we want?

Not all types are sized types (e.g., void, function types, etc). I think currently we don't put any such things in the context yet, but we could put functions in the context when we generate them.

2022-06-10 11:53 UTC, Hchen201205 commented
Complete adding sized-type in context. I added it to all methods (`gen_typ_non_void_size_wo_fn`...) please let me know if I need to take it out from some of them. 

Also, I only start consider types in ctx if the size is greater than 0. Let me know if that needs to change.

Currently adding everything in ctx is a way of letting it to generate more frequent from ctx if ctx is larger. Will change it to freq_LLVM if we want more complicated probability. One way to do it is to map and let each type of ctx to all have same natural number (frequency) that is greater than 1, therefore make it more likely to generate from ctx when ctx is larger. 

Everything should compile.

2022-06-14 13:08 UTC, Chobbes requested changes

2022-06-14 13:08 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        let typs_in_ctx := map (fun '(_, typ) => ret typ) (filter_sized_typs aliases ctx) in
I don't think this should filter sized types.

2022-06-14 13:09 UTC, Chobbes requested changes

2022-06-14 13:09 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        (typs_in_ctx ++ [ gen_sized_typ_0
We should use `freq_LLVM` instead of just relying on the size of `types_in_ctx`.

2022-06-15 10:23 UTC, hanxic commented on src/coq/QC/GenAST.v
> +        let typs_in_ctx := map (fun '(_, typ) => ret typ) (filter_sized_typs aliases ctx) in
I'm assuming you are saying for this function specifically we don't need to filter the types right? I get that because this function uses void and function type.

2022-06-15 15:32 UTC, Chobbes requested changes

2022-06-15 15:32 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        let typs_in_ctx := map (fun '(_, typ) => (1%nat, ret typ)) (filter_sized_typs aliases ctx) in
We should probably use a `filter_non_void_typs` or something. I'm not 100% sure if they'll end up being the same long term, but I think it'd be good to make the distinction for now.

2022-06-15 15:32 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +      freq_LLVM
So, I think we should use `freq_LLVM` like...

`freq_LLVM ([(min (length typs_in_ctx) 10, lift_GenLLVM (elems_ typs_in_ctx))] ++ ...`

Where `typs_in_ctx` is just the filtered context, not mapped into generators or anything. This way we have an upper bound on how frequently this is used.

2022-06-15 18:26 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +      freq_LLVM
So, you are saying, for ctx, we need to first pick a specific type in ctx, and then pick one from it along with all other stuffs not in the ctx (the code in later lines). Couldn't it generate even less probability then the current version (maximum of 10), in which I let every one of the type in ctx to have the same frequency (like 1 or 2, so if we have more than 5 things in the ctx it will jump up to 10).

2022-06-15 19:11 UTC, Chobbes requested changes

2022-06-15 19:11 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        let typs_in_ctx := map (fun '(_, typ) => ret typ) (filter_non_void_typs ctx) in
Let's not map `ret` over all of the types in the context. We can just filter the types in the context and then use `elems_` instead of `oneOf` later.

2022-06-15 19:13 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +        let typs_in_ctx := map (fun '(_, typ) => ret typ) (filter_non_void_typs ctx) in
elems_ takes in a default value. Should the default value just be the type when size 0 is the input?

2022-06-15 19:13 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +      freq_LLVM
I'm not following you.

I don't think we want to make it constantly more likely to generate a type that's already in the context the larger the context is, but the exact weights are something we need to play with #221

2022-06-15 19:15 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +      freq_LLVM
nvm on that. I made the change

2022-06-15 20:05 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +        let typs_in_ctx := map (fun '(_, typ) => ret typ) (filter_non_void_typs ctx) in
Ahhhhhhhh. Right, okay. We should probably add a version of `elems_` with no default later, but this is fine for now then.

2022-06-15 20:07 UTC, merged

2022-06-15 20:07 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +        let typs_in_ctx := map (fun '(_, typ) => ret typ) (filter_non_void_typs ctx) in
ok