Solution for QC stuck issue
vellvm/vellvm pull request #264
Opened 2022-06-24 11:33 UTC by Hchen201205

Solution for issue #221. Solve by bounding the shift operations. Is generating failure cases irrelevant to shift (current record 4 run: 1 success, 3 failure, 0 stuck). Also change the sequence of testing by first going through clang and then go through the interpreter

2022-06-24 12:53 UTC, Chobbes requested changes

2022-06-24 12:53 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +Axiom print_extracted_coq_string : string -> unit.
Clean up.

2022-06-24 12:53 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +  Definition get_bitwidth (z: Z) : Z :=
Why do we need this? Don't we already have the bitwidths?

2022-06-24 12:53 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +  Definition gen_ibinop (t: typ) (ex1 ex2: exp typ) : G ibinop :=
Why change `gen_ibinop`? I think it should stay the same.

2022-06-24 12:53 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +  Definition get_bitwidth (z: Z) : Z :=
Oh, I think you're using this for the shift amount, but you don't have to. If you have an i32 you can only shift between 0 and 31 bits. No need to take the log of anything.

2022-06-24 12:53 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +    let z1 :=
These matches are a bit odd, but we should be able to get rid of them and put `gen_ibinop` back how it was.

2022-06-24 12:53 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +  Definition gen_ibinop (t: typ) (ex1 ex2: exp typ) : G ibinop :=
I think these changes should just be made in `gen_ibinop_exp_typ`.

2022-06-24 12:53 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +      (*let _ := print_extracted_coq_string "tESTing" in*)
Cleanup.

2022-06-24 12:53 UTC, Chobbes commented on src/coq/QC/GenAST.v
> +      (* let bound' := 0%Z in *)
Cleanup.

2022-06-24 12:54 UTC, Chobbes commented
There are the changes to `lib/` coming from?

2022-06-24 12:55 UTC, Hchen201205 commented
I didn't touch it at all. This one is directly copied form memory-testing....

2022-06-26 14:23 UTC, Hchen201205 commented on src/coq/QC/GenAST.v
> +  Definition get_bitwidth (z: Z) : Z :=
Ok, but if we have like i8 4, wouldn't shifting it 7 bits to the left makes it overflow? Or will it just shift to negative

2022-07-11 17:35 UTC, merged