Add simple linker.
vellvm/vellvm pull request #369
Opened 2024-07-08 19:47 UTC by rogerburtonpatel

Added the `link` function, with type ` list toplevel_entity -> list toplevel_entity -> list toplevel_entity`, and introduced it into the `TopLevel` call chain at sites like `interpreter_gen`, `model_gen_*`, etc. 

The code ended up being quite short once I reduced it. Tests and proof of linker postcondition are probably worth it. I'll work on those tomorrow. 

I made type aliases `ll_tle` for `toplevel_entity typ (block typ * list (block typ))`, and
`ll_tle_program` for `list ll_tle`. 
I think this makes the code I wrote and the code that references a variable `(prog : ll_tle_program)` cleaner. 

Lastly, the list of predefined definitions is currently empty. I'll add code to populate it (or hardcode it, depending on your preference) tomorrow.

2024-07-09 13:52 UTC, Chobbes requested changes
Looks good! Left some picky comments :).

2024-07-09 13:52 UTC, Chobbes commented on src/coq/Semantics/TopLevel.v
> +  Definition ll_tle_program := list ll_tle.
In LLVMAst.v we have a `toplevel_entities` already:

```
Definition toplevel_entities (FnBody:Set) : Set := list (@toplevel_entity FnBody).
```

Maybe we should use that, though we would have to pass it the `(block typ * list (block typ))` type.

2024-07-09 13:52 UTC, Chobbes commented on src/coq/Semantics/TopLevel.v
> +        (* add C-O'd lines if we want to expand match *)
What does `C-O'd` mean?

2024-07-09 13:52 UTC, Chobbes commented on src/coq/Semantics/TopLevel.v
> +  Definition decl_defined_in (tle : ll_tle) (tles : ll_tle_program) : bool :=
Nit-picky, but might make sense to specialize this so the `tle` parameter is just the string instead so we get less match-noise. We could even use that as a helper function to define this one.

2024-07-09 13:52 UTC, Chobbes commented on src/coq/Semantics/TopLevel.v
> +         (* | TLE_Definition  {| df_prototype := {| dc_name := Name n |}|} *)
Delete.

2024-07-09 13:52 UTC, Chobbes commented on src/coq/Semantics/TopLevel.v
> +         (* | TLE_Declaration {| dc_name := Name n' |} *)
Delete.

2024-07-09 13:52 UTC, Chobbes commented on src/coq/Semantics/TopLevel.v
> +      let not_predefined := (negb `o` ((flip decl_defined_in) predefs)) in
Maybe we should pull this `(negb `o` ((flip decl_defined_in) predefs))` into a separate named function for readability. Maybe a `is_defined_in` and then we can punt the `negb` into the filter.

2024-07-09 16:47 UTC, rogerburtonpatel commented on src/coq/Semantics/TopLevel.v
> +  Definition ll_tle_program := list ll_tle.
Changed, and renamed to something closer to the original. Lmk what you think. The alias is really just for type annotations below to not spill like crazy.

2024-07-09 16:47 UTC, rogerburtonpatel commented on src/coq/Semantics/TopLevel.v
> +        (* add C-O'd lines if we want to expand match *)
"Commented-Out." Deleted per below so moot now :-)

2024-07-09 16:47 UTC, rogerburtonpatel commented on src/coq/Semantics/TopLevel.v
> +  Definition decl_defined_in (tle : ll_tle) (tles : ll_tle_program) : bool :=
Done.

2024-07-09 16:47 UTC, rogerburtonpatel commented on src/coq/Semantics/TopLevel.v
> +      let not_predefined := (negb `o` ((flip decl_defined_in) predefs)) in
Pulled a bit out. There's a limit to what you can do since `decl_defined_in` or `is_defined_in` needs to take`predefs` as a curried argument to capture it for the call to `filter`. If we assumed that the linker was of type 
`toplevel_entities -> toplevel_entities` (type arguments excluded for brevity), and that the old first argument was _always_ the global predefined functions, then this would be an easy fix:

```
  Definition is_defined_in :  ll_tle -> bool := 
    ((flip decl_defined_in) PREDEFINED_FUNCTIONS) (* PREDEFINED_FUNCTIONS is a global variable *)
```
 That might be restrictive if we intend to build this linker out further. 

For now,

2024-07-09 18:45 UTC, Chobbes commented on src/coq/Semantics/TopLevel.v
> +  Definition ll_tle_program := list ll_tle.
Yeah, honestly I wonder if at some point we should use a proper non-empty list type instead of this tuple thing. We do have a `NonEmpty.v` in Utils already. It's not used much, though. Maybe there's an existing non-empty type in the standard library too.

2024-07-10 16:22 UTC, rogerburtonpatel commented on src/coq/Semantics/TopLevel.v
> +  Definition ll_tle_program := list ll_tle.
See https://github.com/vellvm/vellvm/pull/371!

2024-07-10 16:23 UTC, rogerburtonpatel commented
Ready to merge?

2024-07-12 14:19 UTC, merged